2021-10-28 15:50:57,393 ERROR 75018 [-/127.0.0.1/-/59038ms GET /wxapi/getAccessToken.rjson] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55 -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":2,"requestCount":2,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wy/project/node-log/node_modules/urllib/lib/urllib.js:983:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ConnectionTimeoutError"
requestId: 3
data: undefined
path: "/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":59027,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"],"timing":null,"remoteAddress":"101.226.212.27","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 75018
hostname: wangyangdeMacBook-Pro.local

2021-10-28 15:53:24,578 ERROR 75214 [-/127.0.0.1/-/38200ms GET /wxapi/getAccessToken.rjson] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55 -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wy/project/node-log/node_modules/urllib/lib/urllib.js:983:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ConnectionTimeoutError"
requestId: 1
data: undefined
path: "/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":35189,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"],"timing":null,"remoteAddress":"101.226.212.27","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 75214
hostname: wangyangdeMacBook-Pro.local

2021-10-28 15:53:58,494 ERROR 75214 [-/127.0.0.1/-/15119ms GET /wxapi/getAccessToken.rjson] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55 -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wy/project/node-log/node_modules/urllib/lib/urllib.js:983:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ConnectionTimeoutError"
requestId: 2
data: undefined
path: "/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":7640,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxb0ebfc55a6c688b0&secret=00af2fde7fe01eb04b68cbce80859d55"],"timing":null,"remoteAddress":"101.226.212.27","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 75214
hostname: wangyangdeMacBook-Pro.local

2021-10-28 16:24:48,246 ERROR 76566 [-/127.0.0.1/-/73365ms GET /wxapi/getAccessToken.rjson] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'access_token_expirestime' in 'field list'
    at Query.Sequence._packetToError (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Pool.query (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wy/project/node-log/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/wy/project/node-log/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wy/project/node-log/node_modules/co/index.js:65:19)
    at /Users/wy/project/node-log/node_modules/co/index.js:54:5
    sql: UPDATE `wxconfig` SET `id` = 1, `access_token` = '50_OgNjtZuYBwYJrB4grOEoa_RjvP8FbanSsqS0lINMEzPtn7BDDYN2REw5OvdiAe0kSW-bKEqRKhyF9vLT1IwyunE9jh5yRQ4aHXAHu5TBAq_tm4utiXK3SuGBykTWqg0nhmqtHBpT752fNeFSOWKjACACKY', `access_token_createtime` = 1635409424884, `access_token_expirestime` = 1635416624884 WHERE `id` = 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'access_token_expirestime' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `wxconfig` SET `id` = 1, `access_token` = '50_OgNjtZuYBwYJrB4grOEoa_RjvP8FbanSsqS0lINMEzPtn7BDDYN2REw5OvdiAe0kSW-bKEqRKhyF9vLT1IwyunE9jh5yRQ4aHXAHu5TBAq_tm4utiXK3SuGBykTWqg0nhmqtHBpT752fNeFSOWKjACACKY', `access_token_createtime` = 1635409424884, `access_token_expirestime` = 1635416624884 WHERE `id` = 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 76566
hostname: wangyangdeMacBook-Pro.local

2021-10-28 16:25:54,605 ERROR 76649 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:314:20)
    at Handshake._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol._enqueue (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 76649
hostname: wangyangdeMacBook-Pro.local

2021-10-28 16:28:30,813 ERROR 76786 [-/127.0.0.1/-/13416ms GET /wxapi/getAccessToken.rjson] nodejs.ER_TRUNCATED_WRONG_VALUEError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '1635409704939' for column 'access_token_createtime' at row 1
    at Query.Sequence._packetToError (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    --------------------
    at Pool.query (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/wy/project/node-log/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/wy/project/node-log/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/wy/project/node-log/node_modules/co/index.js:65:19)
    at /Users/wy/project/node-log/node_modules/co/index.js:54:5
    sql: UPDATE `wxconfig` SET `id` = 1, `access_token` = '50_sMhgKf0pfm5bIx6JSms2w4nlJSlRdrLQTauHOZiq3Jr_WTThDkObbtNZtGDOgsPIn3e1HA6bnuMahsXGB4yrmkLjlHX0vB_Jq-YqHbKsQWsfum2T8whFzR36R5_He9bPpshykYQrybAQkeDQUVGcAGAQRC', `access_token_createtime` = 1635409704939, `access_token_expiretime` = 1635416904940 WHERE `id` = 1
code: "ER_TRUNCATED_WRONG_VALUE"
errno: 1292
sqlMessage: "Incorrect datetime value: '1635409704939' for column 'access_token_createtime' at row 1"
sqlState: "22007"
index: 0
sql: "UPDATE `wxconfig` SET `id` = 1, `access_token` = '50_sMhgKf0pfm5bIx6JSms2w4nlJSlRdrLQTauHOZiq3Jr_WTThDkObbtNZtGDOgsPIn3e1HA6bnuMahsXGB4yrmkLjlHX0vB_Jq-YqHbKsQWsfum2T8whFzR36R5_He9bPpshykYQrybAQkeDQUVGcAGAQRC', `access_token_createtime` = 1635409704939, `access_token_expiretime` = 1635416904940 WHERE `id` = 1"
name: "ER_TRUNCATED_WRONG_VALUEError"
pid: 76786
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:10:05,367 ERROR 78566 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:314:20)
    at Handshake._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol._enqueue (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 78566
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:11:52,511 ERROR 78686 [-/127.0.0.1/-/56ms GET /wxapi/getAccessToken.rjson] nodejs.TypeError: Cannot read property 'access_token_expiretime' of null
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/service/wxapi.ts:44:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/controller/wxapi.ts:8:26)
    at /Users/wy/project/node-log/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at xframe (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at xssProtection (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at nosniff (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at noopen (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at session (/Users/wy/project/node-log/node_modules/koa-session/index.js:41:7)
    at bodyParser (/Users/wy/project/node-log/node_modules/koa-bodyparser/index.js:95:5)

pid: 78686
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:12:11,473 ERROR 78686 [-/127.0.0.1/-/26ms GET /wxapi/getAccessToken.rjson] nodejs.TypeError: Cannot read property 'access_token_expiretime' of null
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/service/wxapi.ts:44:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/controller/wxapi.ts:8:26)
    at /Users/wy/project/node-log/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at xframe (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at xssProtection (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at nosniff (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at noopen (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at session (/Users/wy/project/node-log/node_modules/koa-session/index.js:41:7)
    at bodyParser (/Users/wy/project/node-log/node_modules/koa-bodyparser/index.js:95:5)

pid: 78686
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:12:47,316 ERROR 78686 [-/127.0.0.1/-/23ms GET /wxapi/getAccessToken.rjson] nodejs.TypeError: Cannot read property 'access_token_expiretime' of null
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/service/wxapi.ts:44:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Wxapi.getAccessToken (/Users/wy/project/node-log/app/controller/wxapi.ts:8:26)
    at /Users/wy/project/node-log/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at xframe (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at xssProtection (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at nosniff (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at noopen (/Users/wy/project/node-log/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at session (/Users/wy/project/node-log/node_modules/koa-session/index.js:41:7)
    at bodyParser (/Users/wy/project/node-log/node_modules/koa-bodyparser/index.js:95:5)

pid: 78686
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:16:58,056 ERROR 78942 [-/127.0.0.1/-/0ms GET /] nodejs.PROTOCOL_SEQUENCE_TIMEOUTError: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:160:17)
    at Handshake.emit (events.js:314:20)
    at Handshake._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/sequences/Sequence.js:124:8)
    at Timer._onTimeout (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Timer.js:32:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    --------------------
    at Protocol._enqueue (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/wy/project/node-log/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/wy/project/node-log/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/wy/project/node-log/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/wy/project/node-log/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "PROTOCOL_SEQUENCE_TIMEOUT"
fatal: true
timeout: 10000
name: "PROTOCOL_SEQUENCE_TIMEOUTError"
pid: 78942
hostname: wangyangdeMacBook-Pro.local

2021-10-28 17:29:27,484 ERROR 79401 [-/127.0.0.1/-/21446ms GET /wxapi/test.rjson?api=getJsApiTicket] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=50_SqMhneotASG3oYSlXGYiHwmUUTllpdapVocO5J6TvhIJSWKcmrr2w0iDUmSIUyHBzjjvK0aqCUPCtdLe_-Y951h5cafW4j0_OkIqxgQ6STw23OCJ1JKX9ksD_glLpu9g9I2u2kPvhtsnA-USZVKaADALHW&type=jsapi -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (/Users/wy/project/node-log/node_modules/urllib/lib/urllib.js:983:15)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ConnectionTimeoutError"
requestId: 1
data: undefined
path: "/cgi-bin/ticket/getticket?access_token=50_SqMhneotASG3oYSlXGYiHwmUUTllpdapVocO5J6TvhIJSWKcmrr2w0iDUmSIUyHBzjjvK0aqCUPCtdLe_-Y951h5cafW4j0_OkIqxgQ6STw23OCJ1JKX9ksD_glLpu9g9I2u2kPvhtsnA-USZVKaADALHW&type=jsapi"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":8677,"keepAliveSocket":false,"requestUrls":["https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=50_SqMhneotASG3oYSlXGYiHwmUUTllpdapVocO5J6TvhIJSWKcmrr2w0iDUmSIUyHBzjjvK0aqCUPCtdLe_-Y951h5cafW4j0_OkIqxgQ6STw23OCJ1JKX9ksD_glLpu9g9I2u2kPvhtsnA-USZVKaADALHW&type=jsapi"],"timing":null,"remoteAddress":"101.226.212.27","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 79401
hostname: wangyangdeMacBook-Pro.local

